📌 Pause via les boutons Telegram

alias: 🔁 Pause supervision WiFi – Désactivation temporaire
description: >
  Désactive temporairement la supervision WiFi via Telegram,
  puis la réactive automatiquement au bout du délai choisi.
triggers:
  - trigger: event
    event_type: telegram_callback
    event_data:
      data: /disable_wifi_alert_5
  - trigger: event
    event_type: telegram_callback
    event_data:
      data: /disable_wifi_alert_60
  - trigger: event
    event_type: telegram_callback
    event_data:
      data: /disable_wifi_alert_120
  - trigger: event
    event_type: telegram_callback
    event_data:
      data: /disable_wifi_alert_360
  - trigger: event
    event_type: telegram_callback
    event_data:
      data: /disable_wifi_alert_1440

actions:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.supervision_wifi_active

  - service: telegram_bot.send_message
    data:
      message: >
        {% set code = trigger.event.data.data %}
        {% if code == '/disable_wifi_alert_5' %}
          ⏱ Supervision WiFi désactivée pour 5 minutes.
        {% elif code == '/disable_wifi_alert_60' %}
          ⏱ Supervision WiFi désactivée pour 1 heure.
        {% elif code == '/disable_wifi_alert_120' %}
          ⏱ Supervision WiFi désactivée pour 2 heures.
        {% elif code == '/disable_wifi_alert_360' %}
          ⏱ Supervision WiFi désactivée pour 6 heures.
        {% elif code == '/disable_wifi_alert_1440' %}
          ⏱ Supervision WiFi désactivée pour 24 heures.
        {% endif %}

  - delay:
      minutes: >
        {% set code = trigger.event.data.data %}
        {% if code == '/disable_wifi_alert_5' %}5
        {% elif code == '/disable_wifi_alert_60' %}60
        {% elif code == '/disable_wifi_alert_120' %}120
        {% elif code == '/disable_wifi_alert_360' %}360
        {% else %}1440
        {% endif %}

  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.supervision_wifi_active

  - service: telegram_bot.send_message
    data:
      message: "✅ Supervision WiFi réactivée automatiquement."
mode: restart
